import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { HeadingLarge, HeadingMedium } from 'baseui/typography'
import Navbar from '../components/Navbar'
import { Hero } from './index/components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>dev.match()</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
    </>
  )
}

export default Home
