import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import { Hero } from './index/components'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>dev.match()</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Footer />
    </>
  )
}

export default Home
